version: '2'
services:
    xsqljhipster-app:
        image: xsqljhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://xsqljhipster-mysql:3306/xsqljhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=xsqljhipster-elasticsearch:9300
        ports:
            - 8080:8080
    xsqljhipster-mysql:
        extends:
            file: mysql.yml
            service: xsqljhipster-mysql
    xsqljhipster-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: xsqljhipster-elasticsearch
